#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [[ $TAILSCALE_AUTHKEY != "" ]] && [[ ! -f "/var/lib/tailscale/tailscaled.state" ]]; then
  if tailscale up --authkey="${TAILSCALE_AUTHKEY}" --hostname="${TAILSCALE_HOSTNAME:-webtop-xfce4}"; then
     ip=$(tailscale ip -4)
     echo "[tailscale] IP address: $ip"
  else
     echo "[tailscale] Please update your authkey var and restart the container!"
  fi
elif [[ -f "/var/lib/tailscale/tailscaled.state" ]]; then
  echo "[tailscale] State file exists, sleeps in 10 seconds to allow for warmup of deamon"
  ip=$(tailscale ip -4)
  sleep 10
  if tailscale status >>/dev/null; then
    echo "[tailscale] IP address: $ip"
  else
    echo "[tailscale] Session expired, please reauthenicate with 'yarn tailscale-reauth:xfce4-alpine' noninteractively using the"
    echo "[tailscale] authkey parameter to noninteractively authorize the container."
  fi
fi

cd /gclient || exit
HOME="/config" exec \
        s6-setuidgid abc node app.js
