#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [[ $TAILSCALE_AUTHKEY != "" ]] && [[ ! -f "/var/lib/tailscale/tailscaled.state" ]]; then
  if tailscale up --authkey="${TAILSCALE_AUTHKEY}" --hostname="${TAILSCALE_HOSTNAME:-webtop-xfce4}"; then
     ip=$(tailscale ip -4)
     echo "[tailscale] IP address for SSH and RDP: $ip"
  else
     echo "[tailscale] Please update your authkey var and restart the container!"
  fi
elif [[ -f "/var/lib/tailscale/tailscaled.state" ]]; then
  echo "[tailscale] State file exists, sleeps in 10 seconds to allow for warmup of deamon"
  sleep 10
  ip=$(tailscale ip -4)
  if tailscale status >>/dev/null; then
    echo "[tailscale] IP address for: $ip"
  else
    echo "[tailscale] Session expired, please reauthenicate with 'tailscale-reauth' command noninteractively using the"
    echo "[tailscale] authkey parameter inside the container. Do not forget to update the TAILSCALE_AUTHKEY var in your"
    echo "[tailscale] .env file"
  fi
fi

cd /gclient || exit
HOME="/config" exec \
        s6-setuidgid abc node app.js
